export interface Tutor {
    id: string;
    name: string;
    headline: string;
    price: number;
    rating: number;
    reviews: number;
    subjects: string[];
    bio: string;
    image: string;
    yearsExperience: number;
    studentsTaught: number;
    achievements: string[];
    methodology: string;
    linkedin: string;
}

export const tutors: Tutor[] = [
    {
        id: "1",
        name: "Sarah Jenkins",
        headline: "Ex-Google Engineer & Python Expert",
        price: 65,
        rating: 4.9,
        reviews: 124,
        subjects: ["Computer Science", "Python", "Algorithms", "Programming Languages"],
        bio: "I help students master coding interviews and build real-world applications. My background includes 5 years at Google and a CS degree from Stanford.",
        image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 8,
        studentsTaught: 1200,
        achievements: ["Top Rated 2024", "Google Certified"],
        methodology: "Project-based learning with a focus on clean code principles.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "2",
        name: "Dr. Aravind Patel",
        headline: "PhD in Mathematics | Calculus Specialist",
        price: 80,
        rating: 5.0,
        reviews: 89,
        subjects: ["Math", "Calculus", "Linear Algebra"],
        bio: "Mathematics doesn't have to be hard. I break down complex concepts into intuitive visual models. Specializing in high-school and college calculus.",
        image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 15,
        studentsTaught: 3000,
        achievements: ["Best Tutor Award 2023", "Published Author"],
        methodology: "Socratic method combined with visual proofs.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "3",
        name: "Elena Rostova",
        headline: "Data Scientist @ Meta | AI & ML Expert",
        price: 95,
        rating: 5.0,
        reviews: 42,
        subjects: ["Data Science", "Machine Learning", "AI", "Python"],
        bio: "Master the algorithms behind self-driving cars and ChatGPT. I teach Machine Learning, Deep Learning, and Neural Networks using PyTorch and TensorFlow.",
        image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 6,
        studentsTaught: 450,
        achievements: ["Kaggle Grandmaster", "NeurIPS Presenter"],
        methodology: "Theory followed by implementation from scratch.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "4",
        name: "James Wilson",
        headline: "Physics & Chemistry for High Schoolers",
        price: 55,
        rating: 4.7,
        reviews: 156,
        subjects: ["Physics", "Chemistry", "Science"],
        bio: "Making science fun and understandable. We will conduct virtual labs and solve problems that relate to the real world.",
        image: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 10,
        studentsTaught: 1500,
        achievements: ["Science Olympiad Coach", "Teacher of the Year Nominee"],
        methodology: "Inquiry-based learning with real-world applications.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "5",
        name: "Raj Gupta",
        headline: "Full-Stack Dev & Java Spring Boot",
        price: 60,
        rating: 4.8,
        reviews: 110,
        subjects: ["Computer Science", "Java", "Programming Languages", "Web Development"],
        bio: "Specializing in enterprise application development. Learn Java, Spring Boot, and Microservices architecture.",
        image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 12,
        studentsTaught: 900,
        achievements: ["Oracle Certified Professional", "Tech Lead"],
        methodology: "Industry-standard coding content.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "6",
        name: "Michael Chang",
        headline: "Cloud Architect (AWS/Azure) & DevOps",
        price: 110,
        rating: 5.0,
        reviews: 67,
        subjects: ["Cloud Engineering", "DevOps", "AWS", "Computer Science"],
        bio: "Helping you get certified and hired in Cloud. Master Docker, Kubernetes, Terraform, and CI/CD pipelines.",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 9,
        studentsTaught: 400,
        achievements: ["AWS Solutions Architect Pro", "CNCF Ambassador"],
        methodology: "Infrastructure as Code (IaC) first approach.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "7",
        name: "Sophie Turner",
        headline: "History & Social Studies Enthusiast",
        price: 35,
        rating: 4.6,
        reviews: 98,
        subjects: ["History", "Geography", "Social Studies"],
        bio: "History is more than dates; it's a story. I bring the past to life with engaging storytelling and critical analysis.",
        image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 4,
        studentsTaught: 300,
        achievements: ["History Bee Champion", "Summa Cum Laude"],
        methodology: "Connecting historical events to current affairs.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "8",
        name: "David Kim",
        headline: "Biology & Pre-Med Mentor",
        price: 70,
        rating: 4.9,
        reviews: 145,
        subjects: ["Biology", "Chemistry", "Anatomy"],
        bio: "Medical student helping the next generation of doctors. Ace your AP Biology exams and understand the complexity of life.",
        image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 5,
        studentsTaught: 600,
        achievements: ["Med School Scholarship", "Published Researcher"],
        methodology: "Deep understanding of systems and biological processes.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "9",
        name: "Lisa Wang",
        headline: "Mobile App Dev & Swift",
        price: 85,
        rating: 4.8,
        reviews: 55,
        subjects: ["Computer Science", "App Development", "Swift", "Programming Languages"],
        bio: "Turn your app idea into reality. Expert in SwiftUI. I teach the full lifecycle from design to App Store deployment.",
        image: "https://images.unsplash.com/photo-1544717297-fa95b6ee9643?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 7,
        studentsTaught: 250,
        achievements: ["Featured App in App Store", "Hackathon Winner"],
        methodology: "Hands-on coding with a focus on UI/UX.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "10",
        name: "Dr. Marcus Thorne",
        headline: "AI Researcher (NLP & LLMs)",
        price: 120,
        rating: 5.0,
        reviews: 30,
        subjects: ["AI", "Machine Learning", "Data Science", "Computer Science"],
        bio: "Research scientist specializing in Large Language Models and NLP. Learn the cutting edge of AI technology.",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 14,
        studentsTaught: 150,
        achievements: ["PhD in AI", "Cited 500+ times"],
        methodology: "Hardcore theory and research paper implementation.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "11",
        name: "Anita Roy",
        headline: "Primary School Math & Science",
        price: 30,
        rating: 4.9,
        reviews: 350,
        subjects: ["Math", "Science", "English"],
        bio: "Experienced elementary teacher making learning fun for kids! I use games and interactive stories to teach fundamentals.",
        image: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 20,
        studentsTaught: 5000,
        achievements: ["Teacher of the Year", "Early Education Certified"],
        methodology: "Gamified learning and positive reinforcement.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "12",
        name: "Kenji Sato",
        headline: "Japanese Language & Culture",
        price: 50,
        rating: 5.0,
        reviews: 80,
        subjects: ["Languages", "Japanese"],
        bio: "Learn Japanese from a native Tokyoite. I teach not just the language, but the etiquette and culture necessary for fluency.",
        image: "https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 5,
        studentsTaught: 300,
        achievements: ["JLPT N1 Certified Mentor", "Translator"],
        methodology: "Conversation-first approach with rigorous kanji practice.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "13",
        name: "Julia Zhang",
        headline: "IoT & Embedded Systems Engineer",
        price: 80,
        rating: 4.7,
        reviews: 45,
        subjects: ["IoT", "Computer Science", "Programming Languages", "C++"],
        bio: "Connecting the physical world to the digital. Learn Arduino, Raspberry Pi, and RTOS development.",
        image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 8,
        studentsTaught: 600,
        achievements: ["Smart Home Patent", "Embedded Systems Lead"],
        methodology: "Hardware-first approach with hands-on circuits.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "14",
        name: "Omar Farooq",
        headline: "Big Data Engineer (Spark/Hadoop)",
        price: 95,
        rating: 4.8,
        reviews: 70,
        subjects: ["Data Engineering", "Data Science", "SQL", "Python"],
        bio: "Handling petabytes of data is an art. I teach ETL pipelines, Data Warehousing, and distributed computing.",
        image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 10,
        studentsTaught: 500,
        achievements: ["Certified Big Data Professional", "Tech Speaker"],
        methodology: "System design focus on scalability.",
        linkedin: "https://linkedin.com"
    },
    {
        id: "15",
        name: "Priya Sharma",
        headline: "Data Analyst & Dashboarding Expert",
        price: 55,
        rating: 4.6,
        reviews: 130,
        subjects: ["Data Analyst", "Data Science", "SQL", "Tableau"],
        bio: "Turn raw data into actionable insights. Master Excel, SQL, Tableau, and PowerBI visuals.",
        image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop",
        yearsExperience: 6,
        studentsTaught: 1100,
        achievements: ["Data Viz Winner", "Business Intel Lead"],
        methodology: "Storytelling with data.",
        linkedin: "https://linkedin.com"
    }
];
